#include "arcanum/resolver.hpp"

#include <cctype>

namespace arcanum {

std::optional<ResolverOutput> RuleBasedResolver::resolve_symbol(const std::optional<SpellFeatures>&, const std::string& incantation) {
    ResolverOutput out;
    out.spell_name = incantation.empty() ? "Unnamed Sigil" : incantation;

    std::string lower = incantation;
    for (char& c : lower) {
        c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
    }

    if (lower.find("fire") != std::string::npos) out.element = "fire";
    else if (lower.find("ice") != std::string::npos) out.element = "water";
    else if (lower.find("void") != std::string::npos) out.element = "void";
    else out.element = "arcane";

    if (lower.find("shield") != std::string::npos) out.force = "containment";
    else if (lower.find("heal") != std::string::npos) out.force = "healing";
    else if (lower.find("blast") != std::string::npos) out.force = "explosion";
    else out.force = "projection";

    if (lower.find("heal") != std::string::npos) out.intent = "defensive";
    else if (lower.find("ritual") != std::string::npos) out.intent = "ritual";
    else out.intent = "offensive";

    out.scale = "medium";
    out.delivery = out.force == "containment" ? "self" : "projectile";
    out.effect_description = "Rule-based fallback resolver output.";
    out.lore_hint = "Generated by local resolver.";
    out.grammar_analysis = "No AI provider attached.";
    out.misfire_effect = "Reduced potency.";
    out.ambiguity = 0.1f;
    out.base_power = 20;
    out.semantic_tags = {out.element, out.force, out.intent};

    return out;
}

std::optional<ResolverOutput> RuleBasedResolver::resolve_audio(const std::string& transcribed_text) {
    return resolve_symbol(std::nullopt, transcribed_text);
}

} // namespace arcanum
