using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using ArcanumVivum.SpellEngine.Models;

namespace ArcanumVivum.SpellEngine.Resolvers
{
    public sealed class RuleBasedResolver : ISymbolSpellResolver, IAudioSpellResolver
    {
        public Task<ResolverOutput?> ResolveSymbolAsync(SpellFeatures? features, string? incantation, CancellationToken cancellationToken = default)
        {
            var text = (incantation ?? string.Empty).ToLowerInvariant();
            var element = text.Contains("fire") ? "fire"
                : text.Contains("ice") ? "water"
                : text.Contains("void") ? "void"
                : "arcane";

            var force = text.Contains("shield") ? "containment"
                : text.Contains("heal") ? "healing"
                : text.Contains("blast") ? "explosion"
                : "projection";

            var intent = text.Contains("heal") ? "defensive"
                : text.Contains("ritual") ? "ritual"
                : "offensive";

            var output = new ResolverOutput
            {
                SpellName = string.IsNullOrWhiteSpace(incantation) ? "Unnamed Sigil" : incantation!,
                Element = element,
                Force = force,
                Scale = "medium",
                Delivery = force == "containment" ? "self" : "projectile",
                Intent = intent,
                EffectDescription = "Rule-based fallback resolver output.",
                LoreHint = "Generated by local resolver.",
                GrammarAnalysis = "No AI provider attached.",
                MisfireEffect = "Reduced potency.",
                Ambiguity = 0.1f,
                BasePower = 20,
                SemanticTags = new List<string> { element, force, intent }
            };

            return Task.FromResult<ResolverOutput?>(output);
        }

        public Task<ResolverOutput?> ResolveAudioAsync(string transcribedText, CancellationToken cancellationToken = default)
        {
            return ResolveSymbolAsync(null, transcribedText, cancellationToken);
        }
    }
}
