class_name RuleBasedResolver
extends RefCounted

func resolve_symbol(_features: Dictionary, incantation: String) -> Dictionary:
	var text := incantation.to_lower()
	var element := "arcane"
	if text.contains("fire"):
		element = "fire"
	elif text.contains("ice"):
		element = "water"
	elif text.contains("void"):
		element = "void"

	var force := "projection"
	if text.contains("shield"):
		force = "containment"
	elif text.contains("heal"):
		force = "healing"
	elif text.contains("blast"):
		force = "explosion"

	var intent := "offensive"
	if text.contains("heal"):
		intent = "defensive"
	elif text.contains("ritual"):
		intent = "ritual"

	return {
		"spell_name": incantation if not incantation.is_empty() else "Unnamed Sigil",
		"element": element,
		"force": force,
		"scale": "medium",
		"delivery": "self" if force == "containment" else "projectile",
		"intent": intent,
		"effect_description": "Rule-based fallback resolver output.",
		"lore_hint": "Generated by local resolver.",
		"grammar_analysis": "No AI provider attached.",
		"misfire_effect": "Reduced potency.",
		"ambiguity": 0.1,
		"base_power": 20,
		"semantic_tags": [element, force, intent]
	}

func resolve_audio(transcribed_text: String) -> Dictionary:
	return resolve_symbol({}, transcribed_text)
